apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tara-system

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - services/project-service.yaml
  - services/document-service.yaml
  - services/agent-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: tara-system
